### ISSUE TITLE
USER STORY: Manage posts

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#1]
As a **Site Admin** I can **create, read, update and delete posts** so that I can **manage the site's content**

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I am a Site Admin I have access to Django's automatic admin interface where I'm able to create, read, update and delete posts. 

## Tasks:
- [ ] Install Django and supporting libraries
- [ ] Configure files and settings as necessary
- [ ] Add foodiefavourites project and restaurants App
- [ ] Initial deployment
- [ ] Create Restaurant's Post database model
- [ ] Create super user
- [ ] Register Post model to admin.py
- [ ] Install Summernote and configure files and settings as necessary
