### ISSUE TITLE
 USER STORY: Filter posts

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#10]
As a **Site User** I can **filter the available restaurant posts** so that I can **see posts which are more specified to my needs**

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I am a Site User, when looking at a list of restaurant posts to view, I can filter them down using a number of filters.
- Acceptance Criteria 2: Filters must include cuisine, location.

## Tasks:
- [x] Add javascript to visually highlight selected filters. 
- [x] Add hidden form elements to restaurant.html to keep track of which filter has been selected.
- [x] Add javascript to update hidden form elements with filter that has been selected.
- [x] Update RestaurantList view to include necessary queries for particular filters.
- [x] Update RestaurantList view to read GET request information from hidden form elements.
