### ISSUE TITLE
USER STORY: Contact site owners

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#16]
As a **Site User** I can **fill in a contact form** so that I can **get in contact with the site owners to ask any questions I might have**

## Acceptance Criteria:
- Acceptance Criteria 1: A contact form is available to be completed which can be submitted to the site owners.
- Acceptance Criteria 2: Form is easily navigated to.
- Acceptance Criteria 3: Form is unambiguous.

## Tasks:
- [x] Add contact app
- [x] Create ContactForm class within contact app
- [x] Create ContactUs view and related url
- [x] Create and style contact_us.html
