### ISSUE TITLE
USER STORY: Add restaurant post

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#26]
As a Registered Site User I can add my own restaurant posts so that I can share my favourites restaurants and dishes with other users

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I'm a Registered Site User, when signed in I can click on a link to take me to a page which allows me to add a restaurant post of my own.
- Acceptance Criteria 2: The page will contain a form with the relevant fields from the restaurant model.
- Acceptance Criteria 3: Favourite dishes will be a required field where multiple can be added.

## Tasks:
- [ ] Create and style add_restaurant.html template
- [ ] Create AddRestaurant view
- [ ] Link view to template
