### ISSUE TITLE
USER STORY: Delete restaurant post

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#28]
As a **Registered Site User** I can **delete restaurant posts that I've previosuly made** so that I can **remove any restaurant posts that I no longer wish to share**

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I'm a Registered Site User, when signed in and editing one of my own restaurant posts I can click on a link to which will delete the post.
- Acceptance Criteria 2: The must be a page which asks whether or not I definitely wish to delete the post.

## Tasks:
- [ ] Update add_restaurant.html template to include 'Delete' link
- [ ] Create DeleteRestaurant view
- [ ] Link view to template
- [ ] Create restaurant_confirm_delete.html
