### ISSUE TITLE
USER STORY: Update email or password

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#29]
As a **Registered Site User** I can **update my registered email address or update my password** so that I can **use a new email address with my account, strengthen my password or user a more memorable password**

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I'm a Registered Site User, when signed in and on my profile page, I can click on buttons to take me to pages where I can update my registered email address, or update my current password.

## Tasks:
- [x] Make sure email is working in the backend.
- [x] Update and style all email related allauth templates.
- [x] Update and style all password change related allauth templates.
