### ISSUE TITLE
USER STORY: Approve comments

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#3]
As a **Site Admin** I can **approve or disapprove comments** so that I can **filter out any questionable comments**

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I am a Site Admin, when a user adds a comment I then have to manually choose whether or not it gets published by using Django's automatic admin interface.

## Tasks:
- [ ] Create Restaurant's Comment database model
- [ ] Register Comment model in admin.py
- [ ] Configure Comment admin panal to include an "action" to approve comments
