### ISSUE TITLE
 USER STORY: Approve new cuisines

### ISSUE THREAD

**Issue by AshFoster** [AshFoster/foodie-favourites#5]
As a **Site Admin** I can **approve or disapprove suggested new cuisines** so that I can **filter out any questionable cuisines**

## Acceptance Criteria:
- Acceptance Criteria 1: Given that I am a Site Admin, when a user suggests a new cuisine I then have to manually choose whether or not it gets published by using Django's automatic admin interface.

## Tasks:
- [x] Create Restaurant's Cuisine database model
- [x] Register Cuisine model in admin.py
- [x] Configure Cuisine admin panal to include an "action" to approve comments
